---
title: "R Markdown Tutorial"
author: "Yolanda"
date: "8/21/2017"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

# R Markdown General Rule

Notice that the file contains three types of content:

1. An (optional) YAML header surrounded by ---s
2. R code chunks surrounded by ```s
3. text mixed with simple text formatting


## To render the pdf
```{R, eval=FALSE, echo=TRUE}
# Input in the console
library(rmarkdown)
render("/directory/example.Rmd")
```

Or press Command + Shift + K


```{R, echo=TRUE}
# R syntax here
v1 = rnorm(100)
summary(v1)

```


# Formatting text

## Header

A First Level Header
====================

A Second Level Header
---------------------

This is a paragraph

### Header 3

> This is a blockquote.
> 
> This is the second paragraph in the blockquote.
>
> ## This is an H2 in a blockquote

## Emphasize and underline

Words *are emphasized* using a pair of asterisks.

Words can be also _emphasized_ in this way (using a pair of underscores).

Use two asterisks for **strong emphasis**.

Or, __use two underscores instead__.

If you want, ~~strike-through~~.

## Lists
*   Apple.
*   Cherry.
*   Banana.

+   Pineapple.
+   Papaya.
+   Melon.

-   Asia.
-   North America.
-   Europe.

Ordered lists

1.  First
2.  Second
3.  Third

## Link

Inline-style links use parentheses immediately after the link text. For example:

This is an [Formatting Tutorial](https://daringfireball.net/projects/markdown/basics).

This is an [example link](https://daringfireball.net/projects/markdown/basics "Markdown tutorial").

## Math notations ()

Currently html only



**Inline vs Display**

This is an inline: $X_{i}$

This is a display $$X_{i}$$

**Superscript and Subscript**

This is the superscript
y^2^

Subscript
$$X_{i}$$


$$X_{i,j}$$
Both superscript and subscript

$$X^2_{i,j}$$

**Square Root**

Use the sqrt operator
$$\sqrt{b^2 - 4ac}$$

**Fractions**

Use the operator
$$\frac{4z^3}{16}$$

**Summation**
$$\sum_{i=1}^{n} X^3_i$$
**Greek letters**
$$\alpha, \beta,  \gamma, \Gamma$$

**Special Symbols**
$$a \pm b$$
$$x \ge 15$$
$$a_i \ge 0~~~\forall i$$

**Special Functions**
$$\int_0^{2\pi} \sin x~dx$$

**Matrices**

$$\begin{array}
{rrr}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{array}
$$


Another way to present a matrix

$$\mathbf{X} = \left[\begin{array}
{rrr}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{array}\right]
$$


## Examples
We can write fractions: $\frac{2}{3}$. We can also handle things like estimated population growth rate, e.g., $\hat{\lambda}=1.02$. And, $\sqrt{4}=2$.

$$\alpha, \beta,  \gamma, \Gamma$$

$$a \pm b$$
$$x \ge 15$$
$$a_i \ge 0~~~\forall i$$

## Matrix

$$A_{m,n} =
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n}
 \end{pmatrix}$$

## Statistics

The binomial probability: $$f(y|N,p) = \frac{N!}{y!(N-y)!}\cdot p^y \cdot (1-p)^{N-y} = {{N}\choose{y}} \cdot p^y \cdot (1-p)^{N-y}$$

To calculate the **mean** of \textit{n} observations of variable \textit{x}, you can use: $$\bar{x} = \frac{1}{n} \sum_{i=1}^{n}x_{i}$$ 

Note that this equation looks quite nice above where it's in display math mode. It is more compact but not quite as nice looking if we present it using inline mode, e.g., $\bar{x} = \frac{1}{n} \sum_{i=1}^{n}x_{i}$.

Let's do the same with the equation for **variance**. First the inline version, which is 
$\sigma^{2} = \frac{\sum\limits_{i=1}^{n} \left(x_{i} - \bar{x}\right)^{2}} {n-1}$. And then the display mode version: 
$$\sigma^{2} = \frac{\sum_{i=1}^{n} 
  \left(x_{i} - \bar{x}\right)^{2}}
  {n-1}$$
  
And, finally, we'll end with the **standard deviation**. Here's the inline version, $\sigma = \sqrt{\frac{\sum\limits_{i=1}^{n} \left(x_{i} - \bar{x}\right)^{2}} {n-1}}$.

And here's the display version.

$$\sigma = \sqrt{\frac{\sum\limits_{i=1}^{n} \left(x_{i} - \bar{x}\right)^{2}} {n-1}}$$

There are helpful online editors - [check this one out](http://mathstat.uohyd.ernet.in/equationeditor/equationeditor.php)